// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9OpsxIXSuUz9qWF2eUa-i3ClITbU9eAE',
    appId: '1:782247660943:web:e8e9bcf15a844cd5690ffa',
    messagingSenderId: '782247660943',
    projectId: 'reddit-clone-5d9f4',
    authDomain: 'reddit-clone-5d9f4.firebaseapp.com',
    storageBucket: 'reddit-clone-5d9f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8O9gPpn07WJHCehYmXr8RZsHfKoaxpEo',
    appId: '1:782247660943:android:262545e416b83fac690ffa',
    messagingSenderId: '782247660943',
    projectId: 'reddit-clone-5d9f4',
    storageBucket: 'reddit-clone-5d9f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF0fofTlADGzpSoIpq_XTnfYGfmncry44',
    appId: '1:782247660943:ios:306d543a2c9fda42690ffa',
    messagingSenderId: '782247660943',
    projectId: 'reddit-clone-5d9f4',
    storageBucket: 'reddit-clone-5d9f4.appspot.com',
    iosClientId: '782247660943-eappki8mvdi696rnr3ogcb7chfspl1g7.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF0fofTlADGzpSoIpq_XTnfYGfmncry44',
    appId: '1:782247660943:ios:306d543a2c9fda42690ffa',
    messagingSenderId: '782247660943',
    projectId: 'reddit-clone-5d9f4',
    storageBucket: 'reddit-clone-5d9f4.appspot.com',
    iosClientId: '782247660943-eappki8mvdi696rnr3ogcb7chfspl1g7.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
